### PR TITLE
Adds optional ability to enable performance counters for queues.

### PR DESCRIPTION
**Pull request by kbaltrinic**
Corey, 

I did not get a response on my most recent posts in the Rhino Tools forum so I went ahead and made the final changes that I proposed.  This pull contains the BREAKING CHANGE of adding a Start() method to the QueueManager as you recommended.

Please let me know if you have any comments or concerns.  I will be happy to make revisions.

--Ken

### CODE REVIEW

**Comment by kbaltrinic** [comment]
P.S. I forgot to mention that I am still having trouble with intermittent test failures.  All tests pass in isolation but certain tests frequently fail when the entire suite is run.

Two of the most common failures are:

Rhino.Queues.Tests.Monitoring.EnablingPerformanceCounters.Enabling_performance_counters_without_existing_categories_throws_meaningful_error 
  Expected: System.ApplicationException
  Actual:   (No exception was thrown)

Rhino.Queues.Tests.SendingToRhinoQueue.CanSendSeveralMessagesToQueue
  Expected: System.Byte[] { 4, 5, 6, 7 }
  Actual:   System.Byte[] { 6, 7, 8, 9 }

**Comment by CoreyKaylor** [comment]
I should be able to get to this over the weekend. Sorry for the long delay in responding.

**Comment by CoreyKaylor** [comment]
I spent some time last night going through your pull request. This may take more time to review. The tests consistently pass on master and the tests that you mentioned aren't always the ones that fail. When I run the build script several times different tests fail each time. It's likely something simple, but may take some care to figure out where the problem is. I will likely send some more questions along the way.

**Comment by CoreyKaylor** [comment]
Isolating the tests to the same ones that are on the master branch there are still no tests failing. Only when running the newly added tests do things start to randomly fail. Taking a guess here, but it looks like there are a lot of events getting subscribed to, but never getting unsubscribed. This could definitely cause problems.

**Comment by kbaltrinic** [comment]
I will take a look at the event subscription issue and see if that resolves things.

**Comment by kbaltrinic** [comment]
Corey, good call with the event subscriptions.  That seems to have helped but the same two tests identified above still fail, just less frequently now.  I am now getting about one failure for every three test runs.  I should have some time later this week to have another look.  I'll comb the debug logs and see if I can isolate what is going on.

**Comment by kbaltrinic** [comment]
Corey, I believe I have resolved all the issues with the tests.  Indeed my failure to detach the event handlers was the primary problem.  One test was failing intermittently for an unrelated reason which I fixed in 1567498.  All tests are consistently passing now.  Thanks for the help.

**Comment by CoreyKaylor** [comment]
I will try to look at this tomorrow before I go on vacation.

**Pull request merged**
